apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: dev-env
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: shammu101/cycle
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: DATABASE_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: REDIS_PORT
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_MODE
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc1
  namespace: dev-env
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
